CREATE TABLE world_events (
  id serial,
  name text not null,
  start_year integer not null,
  end_year integer not null,
  url text
);

INSERT INTO world_events (name, start_year, end_year, url) VALUES ('Katovuosi', 1527, 1528, null);
INSERT INTO world_events (name, start_year, end_year, url) VALUES ('Kreivisota', 1533, 1536, 'https://fi.wikipedia.org/wiki/Kreivisota');
INSERT INTO world_events (name, start_year, end_year, url) VALUES ('Voudintilejä aletaan laatia', 1537, 1537, null);
INSERT INTO world_events (name, start_year, end_year, url) VALUES ('Katovuosi', 1542, 1542, null);
INSERT INTO world_events (name, start_year, end_year, url) VALUES ('Mikael Agricolan ABC-kirja julkaistaan', 1543, 1543, 'https://fi.wikipedia.org/wiki/Abckiria');
INSERT INTO world_events (name, start_year, end_year, url) VALUES ('Mikael Agricolan Uusi Testamentti julkaistaan', 1548, 1548, 'https://fi.wikipedia.org/wiki/Se_Wsi_Testamenti');
INSERT INTO world_events (name, start_year, end_year, url) VALUES ('Helsinki perustetaan', 1550, 1550, null);
INSERT INTO world_events (name, start_year, end_year, url) VALUES ('Katovuosi', 1551, 1551, null);
INSERT INTO world_events (name, start_year, end_year, url) VALUES ('Suuri Venäjän sota', 1555, 1557, 'https://fi.wikipedia.org/wiki/Suuri_Ven%C3%A4j%C3%A4n_sota');
INSERT INTO world_events (name, start_year, end_year, url) VALUES ('Erik XIV:n ja Juhana III:n veljessota', 1563, 1563, null);
INSERT INTO world_events (name, start_year, end_year, url) VALUES ('Pohjoismaiden seitsenvuotinen sota', 1563, 1570, 'https://fi.wikipedia.org/wiki/Pohjoismaiden_seitsenvuotinen_sota');
INSERT INTO world_events (name, start_year, end_year, url) VALUES ('Perinnöllinen aatelisuus', 1569, 1569, null);
INSERT INTO world_events (name, start_year, end_year, url) VALUES ('Pitkä viha', 1570, 1595, 'https://fi.wikipedia.org/wiki/Pitk%C3%A4_viha');
INSERT INTO world_events (name, start_year, end_year, url) VALUES ('Suomen väkiluku 300 000', 1571, 1571, null);
INSERT INTO world_events (name, start_year, end_year, url) VALUES ('Ensimmäinen kirjallinen merkintä Orimattilasta', 1573, 1573, null);
INSERT INTO world_events (name, start_year, end_year, url) VALUES ('Katovuosi', 1574, 1574, null);
INSERT INTO world_events (name, start_year, end_year, url) VALUES ('Paha katovuosi', 1580, 1580, null);
INSERT INTO world_events (name, start_year, end_year, url) VALUES ('Rutto', 1580, 1580, null);
INSERT INTO world_events (name, start_year, end_year, url) VALUES ('Täyssinän rauha', 1595, 1595, null);
INSERT INTO world_events (name, start_year, end_year, url) VALUES ('Nuijasota', 1596, 1597, 'https://fi.wikipedia.org/wiki/Nuijasota');
INSERT INTO world_events (name, start_year, end_year, url) VALUES ('Ankara katovuosi', 1601, 1602, null);
INSERT INTO world_events (name, start_year, end_year, url) VALUES ('Puolan sota', 1601, 1611, null);
INSERT INTO world_events (name, start_year, end_year, url) VALUES ('Inkerin sota', 1610, 1617, null);
INSERT INTO world_events (name, start_year, end_year, url) VALUES ('Rutto', 1630, 1630, null);
INSERT INTO world_events (name, start_year, end_year, url) VALUES ('Katovuosi', 1631, 1635, null);
INSERT INTO world_events (name, start_year, end_year, url) VALUES ('Läänintilejä aletaan kirjata', 1634, 1634, null);
INSERT INTO world_events (name, start_year, end_year, url) VALUES ('Postilaitos perustetaan Ruotsiin', 1638, 1638, null);
INSERT INTO world_events (name, start_year, end_year, url) VALUES ('Orimattilan seurakunta muodostetaan', 1636, 1636, null);
INSERT INTO world_events (name, start_year, end_year, url) VALUES ('Turun akatemia perustetaan', 1640, 1640, null);
INSERT INTO world_events (name, start_year, end_year, url) VALUES ('Suomenkielinen Raamattu ilmestyy', 1642, 1642, null);
INSERT INTO world_events (name, start_year, end_year, url) VALUES ('Westfalenin rauha', 1648, 1648, null);
INSERT INTO world_events (name, start_year, end_year, url) VALUES ('Katovuosi', 1649, 1650, null);
INSERT INTO world_events (name, start_year, end_year, url) VALUES ('Ruptuurisota', 1656, 1658, 'https://fi.wikipedia.org/wiki/Ruptuurisota');
INSERT INTO world_events (name, start_year, end_year, url) VALUES ('Pohjan sota', 1655, 1660, 'https://fi.wikipedia.org/wiki/Pohjan_sota');
INSERT INTO world_events (name, start_year, end_year, url) VALUES ('Rutto', 1657, 1657, null);
INSERT INTO world_events (name, start_year, end_year, url) VALUES ('Katovuosi', 1664, 1664, null);
INSERT INTO world_events (name, start_year, end_year, url) VALUES ('Suuret kuolonvuodet, kolmasosa suomalaisista kuolee', 1695, 1697, null);
INSERT INTO world_events (name, start_year, end_year, url) VALUES ('Suuri Pohjan sota', 1700, 1721, 'https://fi.wikipedia.org/wiki/Suuri_Pohjan_sota');
INSERT INTO world_events (name, start_year, end_year, url) VALUES ('Isoviha', 1713, 1721, 'https://fi.wikipedia.org/wiki/Isoviha');
INSERT INTO world_events (name, start_year, end_year, url) VALUES ('Hattujen sota', 1741, 1743, 'https://fi.wikipedia.org/wiki/Hattujen_sota');
INSERT INTO world_events (name, start_year, end_year, url) VALUES ('Turun hovioikeus perustetaan', 1623, 1623, null);
INSERT INTO world_events (name, start_year, end_year, url) VALUES ('Suomalaiset 30-vuotisessa sodassa', 1629, 1648, null);
INSERT INTO world_events (name, start_year, end_year, url) VALUES ('Katovuosi', 1680, 1680, null);
INSERT INTO world_events (name, start_year, end_year, url) VALUES ('Kirkkolaki', 1686, 1686, null);
INSERT INTO world_events (name, start_year, end_year, url) VALUES ('Katovuosi', 1690, 1690, null);
INSERT INTO world_events (name, start_year, end_year, url) VALUES ('Katovuosi', 1693, 1693, null);
INSERT INTO world_events (name, start_year, end_year, url) VALUES ('Suomen väkiluku 400 000', 1695, 1695, null);
INSERT INTO world_events (name, start_year, end_year, url) VALUES ('Katovuodet', 1704, 1706, null);
INSERT INTO world_events (name, start_year, end_year, url) VALUES ('Katovuosi', 1708, 1708, null);
INSERT INTO world_events (name, start_year, end_year, url) VALUES ('Paha ruttoepidemia', 1710, 1710, null);
INSERT INTO world_events (name, start_year, end_year, url) VALUES ('Katovuosi', 1726, 1726, null);
INSERT INTO world_events (name, start_year, end_year, url) VALUES ('Katovuosi', 1740, 1740, null);
INSERT INTO world_events (name, start_year, end_year, url) VALUES ('Pikkuviha', 1742, 1743, 'https://fi.wikipedia.org/wiki/Pikkuviha');
INSERT INTO world_events (name, start_year, end_year, url) VALUES ('Gregoriaaninen kalenteri käyttöön', 1753, 1753, null);
INSERT INTO world_events (name, start_year, end_year, url) VALUES ('Katovuosi', 1756, 1756, null);
INSERT INTO world_events (name, start_year, end_year, url) VALUES ('Isojakoasetus', 1757, 1757, null);
INSERT INTO world_events (name, start_year, end_year, url) VALUES ('Suomalaiset tuovat perunan suomeen Pommerin sodasta', 1757, 1762, null);
INSERT INTO world_events (name, start_year, end_year, url) VALUES ('Katovuosi', 1763, 1763, null);
INSERT INTO world_events (name, start_year, end_year, url) VALUES ('Katovuosi', 1769, 1769, null);
INSERT INTO world_events (name, start_year, end_year, url) VALUES ('Ensimmäinen suomalainen sanomalehti', 1771, 1771, null);
INSERT INTO world_events (name, start_year, end_year, url) VALUES ('Katovuosi', 1776, 1776, null);
INSERT INTO world_events (name, start_year, end_year, url) VALUES ('Katovuosi', 1783, 1785, null);
INSERT INTO world_events (name, start_year, end_year, url) VALUES ('Isorokkoepidemia', 1770, 1778, null);
INSERT INTO world_events (name, start_year, end_year, url) VALUES ('Kustaa III:n sota', 1788, 1790, 'https://fi.wikipedia.org/wiki/Kustaa_III:n_sota');
INSERT INTO world_events (name, start_year, end_year, url) VALUES ('Rokotukset aloitetaan', 1797, 1797, null);
INSERT INTO world_events (name, start_year, end_year, url) VALUES ('Suomen sota', 1808, 1809, 'https://fi.wikipedia.org/wiki/Suomen_sota');
INSERT INTO world_events (name, start_year, end_year, url) VALUES ('Ruotsi luovuttaa Suomen Venäjälle', 1809, 1809, null);
INSERT INTO world_events (name, start_year, end_year, url) VALUES ('Suomen pankki perustetaan', 1811, 1811, null);
INSERT INTO world_events (name, start_year, end_year, url) VALUES ('Helsingistä tulee Suomen pääkaupunki', 1812, 1812, null);
INSERT INTO world_events (name, start_year, end_year, url) VALUES ('Kuolemanrangaistus muutetaan karkoitukseksi Siperiaan', 1825, 1825, null);
INSERT INTO world_events (name, start_year, end_year, url) VALUES ('Maailman ensimmäinen valokuva', 1827, 1827, null);
INSERT INTO world_events (name, start_year, end_year, url) VALUES ('Yliopisto siirtyy Turusta Helsinkiin', 1827, 1827, null);
INSERT INTO world_events (name, start_year, end_year, url) VALUES ('Joulukuusi ensimmäisen kerran käytössä Suomessa', 1829, 1829, null);
INSERT INTO world_events (name, start_year, end_year, url) VALUES ('Ankara katovuosi', 1833, 1833, null);
INSERT INTO world_events (name, start_year, end_year, url) VALUES ('Kalevala ilmestyy', 1833, 1833, null);
INSERT INTO world_events (name, start_year, end_year, url) VALUES ('Päijänteen pintaa laskettiin noin 120 cm Kalkkistenkoskea perkaamalla', 1832, 1833, null);
INSERT INTO world_events (name, start_year, end_year, url) VALUES ('Suomen ensimmäinen höyrylaiva Ilmarinen', 1833, 1833, null);
INSERT INTO world_events (name, start_year, end_year, url) VALUES ('Ensimmäinen postimerkki julkaistaan Englannissa', 1840, 1840, null);
INSERT INTO world_events (name, start_year, end_year, url) VALUES ('Suomi siirtyy oikeanpuoleiseen liikenteeseen', 1858, 1858, null);
INSERT INTO world_events (name, start_year, end_year, url) VALUES ('Maamme-laulun ensiesitys', 1848, 1848, null);
INSERT INTO world_events (name, start_year, end_year, url) VALUES ('Sensuuriasetus kieltää suomenkielisten teosten julkaisemisen', 1850, 1850, 'https://fi.wikipedia.org/wiki/Kieliasetus_(1850)');
INSERT INTO world_events (name, start_year, end_year, url) VALUES ('Oolannin sota', 1854, 1856, 'https://fi.wikipedia.org/wiki/Oolannin_sota');
INSERT INTO world_events (name, start_year, end_year, url) VALUES ('Punatautiepidemia', 1851, 1854, null);
INSERT INTO world_events (name, start_year, end_year, url) VALUES ('Saimaan kanava valmistuu', 1856, 1856, null);
INSERT INTO world_events (name, start_year, end_year, url) VALUES ('Suuret nälkävuodet', 1865, 1866, 'https://fi.wikipedia.org/wiki/Suuret_n%C3%A4lk%C3%A4vuodet');
INSERT INTO world_events (name, start_year, end_year, url) VALUES ('Rautatie Helsingistä Hämeenlinnaan', 1862, 1862, null);
INSERT INTO world_events (name, start_year, end_year, url) VALUES ('Suomen markka valuutaksi', 1860, 1860, 'https://fi.wikipedia.org/wiki/Suomen_markka');
INSERT INTO world_events (name, start_year, end_year, url) VALUES ('Katovuosi', 1862, 1862, null);
INSERT INTO world_events (name, start_year, end_year, url) VALUES ('Suomen Yhdyspankki perustetaan', 1862, 1862, null);
INSERT INTO world_events (name, start_year, end_year, url) VALUES ('Kieliasetus mahdollistaa suomen käytön virkakielenä', 1863, 1863, null);
INSERT INTO world_events (name, start_year, end_year, url) VALUES ('Naimattomat naiset vapautuvat isänsä holhouksesta täytettyään 25 v', 1864, 1864, null);
INSERT INTO world_events (name, start_year, end_year, url) VALUES ('Vuoden aikana kuolee 137 700 suomalaista.', 1868, 1868, null);
INSERT INTO world_events (name, start_year, end_year, url) VALUES ('Puhelinlinja Orimattilasta Helsinkiin', 1888, 1888, null);
INSERT INTO world_events (name, start_year, end_year, url) VALUES ('Asevelvollisuuslaki', 1878, 1878, 'https://fi.wikipedia.org/wiki/Suomen_suuriruhtinaskunnan_armeija#Asevelvollisuus');
INSERT INTO world_events (name, start_year, end_year, url) VALUES ('Orimattilan kirkko valmistuu', 1866, 1866, null);
INSERT INTO world_events (name, start_year, end_year, url) VALUES ('Viinan kotipoltto kielletään', 1866, 1866, null);
INSERT INTO world_events (name, start_year, end_year, url) VALUES ('Metrijärjestelmä otetaan käyttöön Suomessa', 1887, 1887, null);
INSERT INTO world_events (name, start_year, end_year, url) VALUES ('Kansallis-Osake-Pankki perustetaan', 1889, 1889, null);
INSERT INTO world_events (name, start_year, end_year, url) VALUES ('Helmikuun manifesti ja Suuri adressi', 1899, 1899, null);
INSERT INTO world_events (name, start_year, end_year, url) VALUES ('Suomen asukasluku 2 656 000', 1900, 1900, null);
INSERT INTO world_events (name, start_year, end_year, url) VALUES ('Kielimanifesti', 1900, 1900, 'https://fi.wikipedia.org/wiki/Kielimanifesti');
INSERT INTO world_events (name, start_year, end_year, url) VALUES ('Ensimmäinen sortokausi', 1899, 1905, 'https://fi.wikipedia.org/wiki/Ensimm%C3%A4inen_sortokausi');
INSERT INTO world_events (name, start_year, end_year, url) VALUES ('Toinen sortokausi', 1908, 1917, 'https://fi.wikipedia.org/wiki/Toinen_sortokausi');
INSERT INTO world_events (name, start_year, end_year, url) VALUES ('Kutsuntalakko', 1902, 1904, 'https://fi.wikipedia.org/wiki/Kutsuntalakko');
INSERT INTO world_events (name, start_year, end_year, url) VALUES ('Eugen Schauman ampuu Bobrikovin', 1904, 1904, null);
INSERT INTO world_events (name, start_year, end_year, url) VALUES ('Suurlakko', 1905, 1905, 'https://fi.wikipedia.org/wiki/Vuoden_1905_suurlakko');
INSERT INTO world_events (name, start_year, end_year, url) VALUES ('Ensimmäinen maailmansota', 1914, 1918, null);
INSERT INTO world_events (name, start_year, end_year, url) VALUES ('Suomi itsenäistyy', 1917, 1917, null);
